// 200 Tyler Durden-coded lines about hot dogs. Surfaced via a small
// optional mascot toast when the user logs a hot dog (or via the
// "What does Tyler say?" button on /hotdogs).
//
// Voice notes: declarative, contrarian, pseudo-philosophical, anti-restraint.
// He's not screaming — he's calmly explaining why the hot dog is the answer.

export const TYLER_LINES: readonly string[] = [
  // — Manifesto core (1–25)
  "The first rule of Hot Dog Club: you talk about Hot Dog Club.",
  "The second rule: you eat the hot dog.",
  "Self-improvement is masturbation. Self-destruction with a hot dog — that's enlightenment.",
  "We are not our gym memberships. We are not our macros. We are the hot dogs we refused to skip.",
  "The things you eat end up eating you. So eat the hot dog first.",
  "You are not your PR. You are the bun.",
  "Reject a future of low-fat. Reject a future of skim. Embrace the dog.",
  "Lose weight slowly, like a marathon. Eat hot dogs quickly, like a man.",
  "It's only after we've lost everything that we are free to order another hot dog.",
  "The amount of hot dog you can carry — that is the measure of you.",
  "I want you to hit me with a hot dog as hard as you can.",
  "On a long enough timeline, the survival rate for everyone drops to zero. So eat the dog now.",
  "Without protein, without bun, without mustard — what are you?",
  "We've all been raised on television to believe that one day we'd all be Brad Pitts. We won't be. But we can have a hot dog right now.",
  "Tomorrow's bench press is a worry. Today's hot dog is a fact.",
  "You met me at a very strange time in my life. I had three hot dogs in my pocket.",
  "I am Jack's complete lack of restraint at a ballpark concession stand.",
  "Sticking feathers up your butt does not make you a chicken. Eating a hot dog makes you yourself.",
  "How much can you know about yourself if you've never eaten a hot dog at 2 a.m.?",
  "The condom is the glass slipper of our generation. The hot dog is the meal.",
  "You're not how much weight you can squat. You're not the watch on your wrist. You are the hot dog of the world.",
  "Fitness apps are diversions. Hot dogs are absolutes.",
  "Reject the salad. Negotiate the hot dog. End the fast.",
  "If you wake up at a different time, in a different place, could you wake up as a different hot dog?",
  "Marla. Marla. Marla. Eat the hot dog.",

  // — Direct encouragement / "go eat one" (26–60)
  "Eat it.",
  "One more hot dog. That's all this life is asking.",
  "There's a hot dog in your future. I can see it.",
  "Stop reading. Go to the kitchen. Boil one.",
  "The grill knows your name.",
  "You owe yourself a wiener.",
  "Right now, somewhere, a hot dog is being grilled. Not for you. Make your own.",
  "The bun is empty. Your hands are full. Reverse it.",
  "You think too much. Eat the dog.",
  "The mustard is patient. The mustard is waiting.",
  "Go on. Just one. You and I both know it won't be one.",
  "There is a tube of meat with your name on it.",
  "Don't be hungry. Be the dog.",
  "Eat one for me. Eat one for you. Eat one for nobody.",
  "Crack the package. Hear the sound. That sound is freedom.",
  "Go ahead. Skip the run. Don't skip the dog.",
  "Open the fridge. Make the call.",
  "Boil. Bun. Bite. Repeat.",
  "Forget the meal prep. Buy the dog.",
  "Stop counting calories. Start counting dogs.",
  "One in the hand. Two in the bun. Three in the soul.",
  "The microwave is a noble servant.",
  "Order the package. Watch the truck come. Live.",
  "You can have your spinach. After the dog.",
  "The grocery store sells hot dogs and lies. You know which one you came for.",
  "Right now: a hot dog. Later: the gym. In that order.",
  "Why are you waiting? The dog isn't waiting.",
  "Tomorrow you'll wish you ate one today.",
  "Eat. The. Dog.",
  "Go. Now. The bun is open.",
  "Stop building character. Start building a hot dog.",
  "Eight. That's a good number. Start there.",
  "Don't take a photo. Don't post it. Just eat it.",
  "The dog doesn't need a caption.",
  "Five hot dogs in five minutes is meditation.",

  // — Anti-restraint, anti-perfection (61–100)
  "Macros are the cage. The hot dog is the key.",
  "Diets are advertising.",
  "Counting calories is a polite way to count regrets.",
  "Restraint is just an unmarketed product.",
  "There is no such thing as a healthy obsession with vegetables.",
  "Kale will not save you.",
  "The sad truth: nobody on their deathbed says, 'I wish I'd eaten more lettuce.'",
  "Your wellness influencer eats hot dogs in the parking lot. You know it.",
  "Moderation is what cowards say to each other.",
  "Do you really want to live forever? Or do you want to live now?",
  "Brunch is for people who are afraid.",
  "Your nutritionist is afraid of the dog.",
  "Skip the smoothie. The smoothie is afraid.",
  "You are not what you eat. You are the friction between you and the bun.",
  "Macros are make-believe.",
  "There is no protein without surrender.",
  "Avocado is a stalling tactic.",
  "If you can spell 'quinoa', you're afraid.",
  "The diet industry needs you small. The hot dog needs nothing.",
  "Cardio without hot dogs is theater.",
  "A clean kitchen is a sad kitchen.",
  "Don't read the label. The label doesn't read you.",
  "We eat because we're hungry. We eat hot dogs because we are alive.",
  "Eating a salad is asking permission.",
  "The hot dog asks no questions.",
  "Hunger is a tool. Use it.",
  "The pantry is a battlefield. The dog is a flag.",
  "There is no clean eating. Only eating.",
  "All food is processed. The hot dog just admits it.",
  "Calories are a fiction by the people who fear them.",
  "Skip the chia seeds. Look yourself in the eye.",
  "Protein powder is a metaphor for not eating a hot dog.",
  "You don't need supplements. You need a snack.",
  "The salad doesn't deserve you.",
  "Lay down your fork. Pick up the dog.",
  "Your body is a temple? Then this is an offering.",
  "You can't out-train a hot dog. So eat one and stop trying.",
  "Counting macros is rearranging deck chairs.",
  "There is no 'cheat day'. There is only the day.",
  "Stop optimizing. Start eating.",

  // — Philosophical (101–135)
  "We are stardust. We are golden. We are 290 calories of pure, defiant beef.",
  "The bun and the meat: a marriage. The mustard: the witness.",
  "All hot dogs are the same hot dog, in a sense.",
  "Time moves slower with a hot dog in hand.",
  "When you bite, you are bitten. When you eat, you are eaten.",
  "There is no dog. Only the dog.",
  "Some men chase enlightenment. Some men chase the ice cream truck. Some men are home, with a hot dog.",
  "Memory is unreliable. The hot dog is reliable.",
  "Suffering builds character. So does the second hot dog.",
  "If you have to ask 'should I?', you should.",
  "What is a hot dog? An offering wrapped in a bun.",
  "Time is a flat hot dog.",
  "We eat to remember. We eat hot dogs to forget.",
  "The bun is the canvas. The dog is the paint.",
  "Mustard is yellow. So is the sun. So is courage.",
  "There is a stillness inside the bun.",
  "All things end. The dog ends in your mouth, where it should.",
  "I refuse to die without one more.",
  "The hot dog does not negotiate.",
  "Each hot dog is a small sermon.",
  "We are all hot dogs in our hearts, waiting to be eaten by life.",
  "Joy is the moment you commit to a hot dog without regret.",
  "There are no atheists in front of a hot dog cart.",
  "The bun is forgiving. The judge is not.",
  "Two hot dogs is one hot dog twice.",
  "Hunger lies. The hot dog tells the truth.",
  "Ketchup is a confession.",
  "All buns are temples. Some have meat in them.",
  "The relish whispers: 'I was here.'",
  "Choose the dog. The dog is choosing you.",
  "When in doubt, mustard.",
  "When not in doubt, also mustard.",
  "A hot dog and a moon. That's all it takes.",
  "The dog is older than you. The dog is wiser than you.",
  "We don't have a hot dog problem. We have a not-eating-a-hot-dog problem.",

  // — Workout-tied (136–165)
  "You earned that hot dog the moment you racked the bar.",
  "Squats build legs. Hot dogs build character.",
  "Deadlift, hot dog, repeat. That's the gospel.",
  "Pre-workout is fear. Post-workout is hot dog.",
  "Bench press today, hot dog tonight, glory tomorrow.",
  "There is no gain without bun.",
  "Recovery is a hot dog you ate yesterday.",
  "Drink water. Eat dog. Lift heavy.",
  "Three sets of five hot dogs is a complete program.",
  "Grease is electrolytes.",
  "The protein shake is jealous of the dog.",
  "Run a mile. Eat a dog. Sleep a sleep.",
  "Carbs cycle. So do hot dogs.",
  "Bulk season is just hot dog season with a name.",
  "The wiener is a dumbbell. The bun is the rack.",
  "Five reps. Five dogs. Five fingers.",
  "On rest days, the dog rests with you.",
  "Sundays are for wieners.",
  "Cold plunge after. Hot dog before.",
  "Mind muscle connection means thinking about the dog.",
  "Volume is the weight × reps × hot dogs.",
  "Hypertrophy: eating more hot dogs than you used to.",
  "Strict press, strict mustard.",
  "Failure is when you put the dog down before finishing.",
  "Cardio is just an excuse to earn a dog.",
  "Mobility work is for people who can't reach the second dog.",
  "Bro split? More like dog split.",
  "Push, pull, legs, hot dog.",
  "Conditioning: doing more hot dogs in less time.",
  "Tempo is for people who don't have hot dogs to eat.",

  // — Streetwise / quotable (166–200)
  "On the long drive home from the gym, the hot dog drives.",
  "I haven't been this excited since I bought the second pack.",
  "Hot dog night is every night with the right attitude.",
  "I had a stranger's hot dog once. I never forgot.",
  "The hot dog is the original meal kit.",
  "You ever notice how hot dogs come in 10 and buns in 8? That's the system, man.",
  "All-beef. That's the only kind of vow that matters.",
  "I respect a man who doesn't ask which dog. The dog has been chosen.",
  "Trust the dog. The dog has done this before.",
  "The hot dog: never broken, never sorry.",
  "Some people see the bun half full. I see two hot dogs.",
  "If you can't eat a hot dog in front of your boss, you have the wrong boss.",
  "I lost respect for chefs the day I made my first hot dog.",
  "Order in. Eat out. Eat the dog regardless.",
  "Plant-based wieners are still wieners. We accept all.",
  "Garnish is a request for permission.",
  "The relish is the punctuation.",
  "Don't bring kale to a hot dog fight.",
  "If the bun bursts, eat faster.",
  "The pickle is a witness, not an obstacle.",
  "Onions are a dare.",
  "Sauerkraut is a haiku.",
  "Texas style: beans, no chili, no fear.",
  "Chicago dogs are governments. New York dogs are anarchies. Both are right.",
  "I never met a hot dog I owed anything to. We're square.",
  "I never meet a man at his best who isn't on his second dog.",
  "You can keep your aged steak. I'll take the next one off the roller.",
  "Gas station hot dog is the only food that improves with mileage.",
  "I trust a man who finishes his dog without setting it down.",
  "Last meal? Don't insult me. Last hot dog.",
  "If you're nervous, eat. If you're calm, eat. If you're alive, eat.",
  "The dog will not love you back. The dog does not have to.",
  "There's only one move I'll teach you. Bite.",
  "When the world ends, I want to be in the bun line.",
  "Eat one for the road. Eat one for the home. Eat one for the spaces in between.",
] as const;

export function pickTylerLine(): string {
  return TYLER_LINES[Math.floor(Math.random() * TYLER_LINES.length)];
}
